version: '3.1'

networks:
  epas:
    external: true

services:

###    Le variabili volumes sono mappate come - host_folder:container_folder
###    Correggere all'occorrenza i path per le cartelle sull'host ma lasciare inalterati i path sui container docker  

  epas:
    #image: docker-registry.services.iit.cnr.it/epas/epas:stable
    image: criluc/epas:telework-1
    container_name: epas
    ports:
     - 9000:9000
    networks:
      - epas
    volumes:
      - ./docker-data/logs:/home/epas/epas/logs
      #- ./epas/attachments:/home/epas/epas/data/attachments
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    labels:
      - traefik.enable=true
      - traefik.backend=epas
      - traefik.frontend.rule=Host:${HOST_NAME}
      - traefik.port=9000
    environment:
      - VIRTUAL_HOST=${HOST_NAME}
      #- PROTOCOL=https                         # default: http  -- (http,https)
      #      - EPAS_SHIB_LOGIN=                      # default: false  -- (true,false)
      #- JOBS_ACTIVE=true                       # default: false  -- (true,false) --  Se forzato a true abilita l'esecuzione di tutti i job
      #      - SKIP_IP_CHECK=                        # default: false -- (true,false) -- Disabilita il controllo sugli indirizzi ip delle richieste
      - FLOWS_ACTIVE=true
      #      - URL_ATTESTATI=                        # default: https://attestativ2.rm.cnr.it
      #      - URL_USER=
      #      - URL_PASS=
      ######## LOGS ###########
      #      - LOG_LEVEL=                            # Opzionale. default: INFO   -- (OFF,FATAL,ERROR,WARN,INFO,DEBUG,TRACE,ALL)
      - APPENDERS=file                        # Opzionale. default: stdout, stderr -- (stdout, stderr, file, graylog2). Abilita i log sulla console, file e server graylog
      #      - GRAYLOG_HOST=                         # Obbligatorio se attivato log sull'appender graylog2. default: null
      #      - GRAYLOG_PORT=                         # Opzionale. default: 3514
      #      - GRAYLOG_ORIGIN_HOST=                  # Opzionale. default: valore in VIRTUAL_HOST
      ###### Container ########
      #      - BACKUP_CRON=                          # default: disattivato. (utilizzare il format del crontab. Es. 0 0 * * *)
      #      - CERT_NAME=                            # default: valore specificato in VIRTUAL_HOST -- Specifica un nome diverso per i file del certificato SSL
      - TZ=Europe/Rome
      #### Connessione DB ####
      - DB_HOST=${DB_HOST}                     # default: indirizzo assegnato al container postgres linkato
      - DB_NAME=${DB_NAME}                     # default: epas
      - DB_PASS=${DB_PASS}                     # default: "non necessaria"
      - DB_PORT=5432                           # default: 5432
      - DB_USER=${DB_USER}                     # default: postgres
      #### server SMTP ####
      - SMTP_HOST=${SMTP_HOST}                # default: smtp.cnr.it
      #- SMTP_PORT=${SMTP_PORT}                # default: 25 se SMTP_CHANNEL Ã¨ impostato clear o starttls; 465 se impostato su ssl
#      - SMTP_CHANNEL=${SMTP_CHANNEL}          # default: clear -- (clear, ssl ,starttls)
      #- SMTP_FROM=${SMTP_FROM}                # default: epas@cnr.it -- Indirizzo utilizzato per il campo mittente delle mail inviate dal sistema
      #- SMTP_PROTOCOL=${SMTP_PROTOCOL}        # default: smtp -- (smtp, smtps)
      #- SMTP_USER=${SMTP_USER}                # user utilizzato per l'autenticazione sul server smtp (se necessario)
      #- SMTP_PASS=${SMTP_PASS}                # password utilizzato per l'autenticazione sul server smtp (se necessaria)
      #### Autenticazione LDAP ####
      #- LDAP_LOGIN=true                       # default: false. Impostare a true per attivare l'autenticazione tramite LDAP
      #- LDAP_URL=${LDAP_URL}                  # url del server LDAP, per esempio ldap://ldap.cnr.it:389
      #      - LDAP_TIMEOUT=${LDAP_TIMEOUT}          # default: 1000. Time in millisecondi della connessione LDAP.
      #- LDAP_DN_BASE=${LDAP_DN_BASE}          # DN per la ricerca degli utenti su LDAP, per esempio ou=People,dc=iit,dc=cnr,dc=it
      #      - LDAP_LOGIN_RETURN=${LDAP_LOGIN_RETURN} # default: /. Indirizzo relativo di reindirizzamento dopo il login LDAP.
      #      - LDAP_EPPN_ATTRIBUTE_NAME=${LDAP_EPPN_ATTRIBUTE_NAME}  # default: eduPersonPrincipalName. Campo LDAP utilizzato per il mapping con il campo eppn presente in ePAS.
      #### Invio Segnalazioni via email
      #- REPORT_TO=${REPORT_TO}                 # default: epas@iit.cnr.it
      #- REPORT_FROM=${REPORT_FROM}             # default: segnalazioni@epas.tools.iit.cnr.it
      #- REPORT_SUBJECT=${REPORT_SUBJECT}       # default: Segnalazione ePAS
      #- TELEWORK_ACTIVE=${TELEWORK_ACTIVE}   # default: false
      #- TELEWORK_BASEURL=${TELEWORK_BASEURL}   # default: http://telework-stampings:8080
      #- TELEWORK_USER=${TELEWORK_USER}   # default: app.epas
      #- TELEWORK_PASS=${TELEWORK_PASS}   # default: chiedere al team di sviluppo

    restart: unless-stopped

